# Copyright (c) 2018 TOYOTA MOTOR CORPORATION
# All rights reserved.

# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:

#  * Redistributions of source code must retain the above copyright notice,
#  this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above copyright
#  notice, this list of conditions and the following disclaimer in the
#  documentation and/or other materials provided with the distribution.
#  * Neither the name of Toyota Motor Corporation nor the names of its
#  contributors may be used to endorse or promote products derived from
#  this software without specific prior written permission.

# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
robot_base_frame: base_link

transform_tolerance: 0.5

robot_radius: 0.15
inflater:
  robot_radius: 0.15
  inflation_radius: 0.15

obstacles:
  observation_sources: base_scan obstacles
  enabled:              true
  max_obstacle_height: 2.0
  obstacle_range: 2.5
  combination_method: 1

  base_scan:
    data_type: LaserScan
    topic: hsrb/base_scan
    marking: true
    clearing: true
    obstacle_range: 6.0
    raytrace_range: 10.0
    min_obstacle_height: 0.1
    max_obstacle_height: 0.3

  obstacles:
    data_type: PointCloud2
    topic: obstacles
    marking: true
    clearing: true
    obstacle_range: 6.0
    raytrace_range: 10.0
    min_obstacle_height: 0.0
    max_obstacle_height: 1.0
